/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package hello.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-5-16")
public class Demo implements org.apache.thrift.TBase<Demo, Demo._Fields>, java.io.Serializable, Cloneable, Comparable<Demo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Demo");

  private static final org.apache.thrift.protocol.TField DEMO_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("demoName", org.apache.thrift.protocol.TType.STRING, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DemoStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DemoTupleSchemeFactory());
  }

  public String demoName; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DEMO_NAME((short)1, "demoName");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DEMO_NAME
          return DEMO_NAME;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.DEMO_NAME};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DEMO_NAME, new org.apache.thrift.meta_data.FieldMetaData("demoName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Demo.class, metaDataMap);
  }

  public Demo() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Demo(Demo other) {
    if (other.isSetDemoName()) {
      this.demoName = other.demoName;
    }
  }

  public Demo deepCopy() {
    return new Demo(this);
  }

  @Override
  public void clear() {
    this.demoName = null;
  }

  public String getDemoName() {
    return this.demoName;
  }

  public Demo setDemoName(String demoName) {
    this.demoName = demoName;
    return this;
  }

  public void unsetDemoName() {
    this.demoName = null;
  }

  /** Returns true if field demoName is set (has been assigned a value) and false otherwise */
  public boolean isSetDemoName() {
    return this.demoName != null;
  }

  public void setDemoNameIsSet(boolean value) {
    if (!value) {
      this.demoName = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case DEMO_NAME:
      if (value == null) {
        unsetDemoName();
      } else {
        setDemoName((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case DEMO_NAME:
      return getDemoName();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case DEMO_NAME:
      return isSetDemoName();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Demo)
      return this.equals((Demo)that);
    return false;
  }

  public boolean equals(Demo that) {
    if (that == null)
      return false;

    boolean this_present_demoName = true && this.isSetDemoName();
    boolean that_present_demoName = true && that.isSetDemoName();
    if (this_present_demoName || that_present_demoName) {
      if (!(this_present_demoName && that_present_demoName))
        return false;
      if (!this.demoName.equals(that.demoName))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_demoName = true && (isSetDemoName());
    list.add(present_demoName);
    if (present_demoName)
      list.add(demoName);

    return list.hashCode();
  }

  @Override
  public int compareTo(Demo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetDemoName()).compareTo(other.isSetDemoName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDemoName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.demoName, other.demoName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Demo(");
    boolean first = true;

    if (isSetDemoName()) {
      sb.append("demoName:");
      if (this.demoName == null) {
        sb.append("null");
      } else {
        sb.append(this.demoName);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DemoStandardSchemeFactory implements SchemeFactory {
    public DemoStandardScheme getScheme() {
      return new DemoStandardScheme();
    }
  }

  private static class DemoStandardScheme extends StandardScheme<Demo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Demo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DEMO_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.demoName = iprot.readString();
              struct.setDemoNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Demo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.demoName != null) {
        if (struct.isSetDemoName()) {
          oprot.writeFieldBegin(DEMO_NAME_FIELD_DESC);
          oprot.writeString(struct.demoName);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DemoTupleSchemeFactory implements SchemeFactory {
    public DemoTupleScheme getScheme() {
      return new DemoTupleScheme();
    }
  }

  private static class DemoTupleScheme extends TupleScheme<Demo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Demo struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetDemoName()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDemoName()) {
        oprot.writeString(struct.demoName);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Demo struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.demoName = iprot.readString();
        struct.setDemoNameIsSet(true);
      }
    }
  }

}

