/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "base_constants.h"

namespace com { namespace example { namespace project {

const baseConstants g_base_constants;

baseConstants::baseConstants() {
}

}}} // namespace

