/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Twitter_H
#define Twitter_H

#include <thrift/TDispatchProcessor.h>
#include "base_types.h"

namespace com { namespace example { namespace project {

class TwitterIf {
 public:
  virtual ~TwitterIf() {}
  virtual void ping() = 0;
  virtual bool postTweet(const Tweet& tweet) = 0;
  virtual int32_t searchTweets(const std::string& query) = 0;
  virtual void zip() = 0;
};

class TwitterIfFactory {
 public:
  typedef TwitterIf Handler;

  virtual ~TwitterIfFactory() {}

  virtual TwitterIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(TwitterIf* /* handler */) = 0;
};

class TwitterIfSingletonFactory : virtual public TwitterIfFactory {
 public:
  TwitterIfSingletonFactory(const boost::shared_ptr<TwitterIf>& iface) : iface_(iface) {}
  virtual ~TwitterIfSingletonFactory() {}

  virtual TwitterIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(TwitterIf* /* handler */) {}

 protected:
  boost::shared_ptr<TwitterIf> iface_;
};

class TwitterNull : virtual public TwitterIf {
 public:
  virtual ~TwitterNull() {}
  void ping() {
    return;
  }
  bool postTweet(const Tweet& /* tweet */) {
    bool _return = false;
    return _return;
  }
  int32_t searchTweets(const std::string& /* query */) {
    int32_t _return = 0;
    return _return;
  }
  void zip() {
    return;
  }
};


class Twitter_ping_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Twitter_ping_args(const Twitter_ping_args&);
  Twitter_ping_args& operator=(const Twitter_ping_args&);
  Twitter_ping_args() {
  }

  virtual ~Twitter_ping_args() throw();

  bool operator == (const Twitter_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Twitter_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_ping_args& obj);
};


class Twitter_ping_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Twitter_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_ping_pargs& obj);
};


class Twitter_ping_result {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Twitter_ping_result(const Twitter_ping_result&);
  Twitter_ping_result& operator=(const Twitter_ping_result&);
  Twitter_ping_result() {
  }

  virtual ~Twitter_ping_result() throw();

  bool operator == (const Twitter_ping_result & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Twitter_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_ping_result& obj);
};


class Twitter_ping_presult {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Twitter_ping_presult() throw();

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Twitter_ping_presult& obj);
};

typedef struct _Twitter_postTweet_args__isset {
  _Twitter_postTweet_args__isset() : tweet(false) {}
  bool tweet :1;
} _Twitter_postTweet_args__isset;

class Twitter_postTweet_args {
 public:

  static const char* ascii_fingerprint; // = "915F1A3C84CB5B86264227E2807BA7DA";
  static const uint8_t binary_fingerprint[16]; // = {0x91,0x5F,0x1A,0x3C,0x84,0xCB,0x5B,0x86,0x26,0x42,0x27,0xE2,0x80,0x7B,0xA7,0xDA};

  Twitter_postTweet_args(const Twitter_postTweet_args&);
  Twitter_postTweet_args& operator=(const Twitter_postTweet_args&);
  Twitter_postTweet_args() {
  }

  virtual ~Twitter_postTweet_args() throw();
  Tweet tweet;

  _Twitter_postTweet_args__isset __isset;

  void __set_tweet(const Tweet& val);

  bool operator == (const Twitter_postTweet_args & rhs) const
  {
    if (!(tweet == rhs.tweet))
      return false;
    return true;
  }
  bool operator != (const Twitter_postTweet_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_postTweet_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_postTweet_args& obj);
};


class Twitter_postTweet_pargs {
 public:

  static const char* ascii_fingerprint; // = "915F1A3C84CB5B86264227E2807BA7DA";
  static const uint8_t binary_fingerprint[16]; // = {0x91,0x5F,0x1A,0x3C,0x84,0xCB,0x5B,0x86,0x26,0x42,0x27,0xE2,0x80,0x7B,0xA7,0xDA};


  virtual ~Twitter_postTweet_pargs() throw();
  const Tweet* tweet;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_postTweet_pargs& obj);
};

typedef struct _Twitter_postTweet_result__isset {
  _Twitter_postTweet_result__isset() : success(false), unavailable(false) {}
  bool success :1;
  bool unavailable :1;
} _Twitter_postTweet_result__isset;

class Twitter_postTweet_result {
 public:

  static const char* ascii_fingerprint; // = "FB3C6215AF7D1EFB061C9941F4721D27";
  static const uint8_t binary_fingerprint[16]; // = {0xFB,0x3C,0x62,0x15,0xAF,0x7D,0x1E,0xFB,0x06,0x1C,0x99,0x41,0xF4,0x72,0x1D,0x27};

  Twitter_postTweet_result(const Twitter_postTweet_result&);
  Twitter_postTweet_result& operator=(const Twitter_postTweet_result&);
  Twitter_postTweet_result() : success(0) {
  }

  virtual ~Twitter_postTweet_result() throw();
  bool success;
  TwitterUnavailable unavailable;

  _Twitter_postTweet_result__isset __isset;

  void __set_success(const bool val);

  void __set_unavailable(const TwitterUnavailable& val);

  bool operator == (const Twitter_postTweet_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    if (!(unavailable == rhs.unavailable))
      return false;
    return true;
  }
  bool operator != (const Twitter_postTweet_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_postTweet_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_postTweet_result& obj);
};

typedef struct _Twitter_postTweet_presult__isset {
  _Twitter_postTweet_presult__isset() : success(false), unavailable(false) {}
  bool success :1;
  bool unavailable :1;
} _Twitter_postTweet_presult__isset;

class Twitter_postTweet_presult {
 public:

  static const char* ascii_fingerprint; // = "FB3C6215AF7D1EFB061C9941F4721D27";
  static const uint8_t binary_fingerprint[16]; // = {0xFB,0x3C,0x62,0x15,0xAF,0x7D,0x1E,0xFB,0x06,0x1C,0x99,0x41,0xF4,0x72,0x1D,0x27};


  virtual ~Twitter_postTweet_presult() throw();
  bool* success;
  TwitterUnavailable unavailable;

  _Twitter_postTweet_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Twitter_postTweet_presult& obj);
};

typedef struct _Twitter_searchTweets_args__isset {
  _Twitter_searchTweets_args__isset() : query(false) {}
  bool query :1;
} _Twitter_searchTweets_args__isset;

class Twitter_searchTweets_args {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  Twitter_searchTweets_args(const Twitter_searchTweets_args&);
  Twitter_searchTweets_args& operator=(const Twitter_searchTweets_args&);
  Twitter_searchTweets_args() : query() {
  }

  virtual ~Twitter_searchTweets_args() throw();
  std::string query;

  _Twitter_searchTweets_args__isset __isset;

  void __set_query(const std::string& val);

  bool operator == (const Twitter_searchTweets_args & rhs) const
  {
    if (!(query == rhs.query))
      return false;
    return true;
  }
  bool operator != (const Twitter_searchTweets_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_searchTweets_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_searchTweets_args& obj);
};


class Twitter_searchTweets_pargs {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};


  virtual ~Twitter_searchTweets_pargs() throw();
  const std::string* query;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_searchTweets_pargs& obj);
};

typedef struct _Twitter_searchTweets_result__isset {
  _Twitter_searchTweets_result__isset() : success(false) {}
  bool success :1;
} _Twitter_searchTweets_result__isset;

class Twitter_searchTweets_result {
 public:

  static const char* ascii_fingerprint; // = "32183C4A04E706C58ED2F62566DDD8DE";
  static const uint8_t binary_fingerprint[16]; // = {0x32,0x18,0x3C,0x4A,0x04,0xE7,0x06,0xC5,0x8E,0xD2,0xF6,0x25,0x66,0xDD,0xD8,0xDE};

  Twitter_searchTweets_result(const Twitter_searchTweets_result&);
  Twitter_searchTweets_result& operator=(const Twitter_searchTweets_result&);
  Twitter_searchTweets_result() : success(0) {
  }

  virtual ~Twitter_searchTweets_result() throw();
  int32_t success;

  _Twitter_searchTweets_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const Twitter_searchTweets_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Twitter_searchTweets_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_searchTweets_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_searchTweets_result& obj);
};

typedef struct _Twitter_searchTweets_presult__isset {
  _Twitter_searchTweets_presult__isset() : success(false) {}
  bool success :1;
} _Twitter_searchTweets_presult__isset;

class Twitter_searchTweets_presult {
 public:

  static const char* ascii_fingerprint; // = "32183C4A04E706C58ED2F62566DDD8DE";
  static const uint8_t binary_fingerprint[16]; // = {0x32,0x18,0x3C,0x4A,0x04,0xE7,0x06,0xC5,0x8E,0xD2,0xF6,0x25,0x66,0xDD,0xD8,0xDE};


  virtual ~Twitter_searchTweets_presult() throw();
  int32_t* success;

  _Twitter_searchTweets_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const Twitter_searchTweets_presult& obj);
};


class Twitter_zip_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Twitter_zip_args(const Twitter_zip_args&);
  Twitter_zip_args& operator=(const Twitter_zip_args&);
  Twitter_zip_args() {
  }

  virtual ~Twitter_zip_args() throw();

  bool operator == (const Twitter_zip_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Twitter_zip_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Twitter_zip_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_zip_args& obj);
};


class Twitter_zip_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~Twitter_zip_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Twitter_zip_pargs& obj);
};

class TwitterClient : virtual public TwitterIf {
 public:
  TwitterClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  TwitterClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping();
  void send_ping();
  void recv_ping();
  bool postTweet(const Tweet& tweet);
  void send_postTweet(const Tweet& tweet);
  bool recv_postTweet();
  int32_t searchTweets(const std::string& query);
  void send_searchTweets(const std::string& query);
  int32_t recv_searchTweets();
  void zip();
  void send_zip();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class TwitterProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<TwitterIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (TwitterProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_postTweet(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_searchTweets(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_zip(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  TwitterProcessor(boost::shared_ptr<TwitterIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &TwitterProcessor::process_ping;
    processMap_["postTweet"] = &TwitterProcessor::process_postTweet;
    processMap_["searchTweets"] = &TwitterProcessor::process_searchTweets;
    processMap_["zip"] = &TwitterProcessor::process_zip;
  }

  virtual ~TwitterProcessor() {}
};

class TwitterProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  TwitterProcessorFactory(const ::boost::shared_ptr< TwitterIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< TwitterIfFactory > handlerFactory_;
};

class TwitterMultiface : virtual public TwitterIf {
 public:
  TwitterMultiface(std::vector<boost::shared_ptr<TwitterIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~TwitterMultiface() {}
 protected:
  std::vector<boost::shared_ptr<TwitterIf> > ifaces_;
  TwitterMultiface() {}
  void add(boost::shared_ptr<TwitterIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    ifaces_[i]->ping();
  }

  bool postTweet(const Tweet& tweet) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->postTweet(tweet);
    }
    return ifaces_[i]->postTweet(tweet);
  }

  int32_t searchTweets(const std::string& query) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->searchTweets(query);
    }
    return ifaces_[i]->searchTweets(query);
  }

  void zip() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->zip();
    }
    ifaces_[i]->zip();
  }

};

}}} // namespace

#endif
